version: "3.8"
name: irlhistory
services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    env_file:
      - ./services/auth-service/Config/dev.env
    networks:
      - services-network
    develop:
      watch:
        - path: ./services/auth-service/package.json
          action: rebuild
        - path: ./services/auth-service/package-lock.json
          action: rebuild
        - path: ./services/auth-service/Config/dev.env
          action: rebuild
        - path: ./services/auth-service
          target: /app
          action: sync

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - 6000:6000
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./services/user-service/Config/dev.env
    networks:
      - services-network
    develop:
      watch:
        - path: ./services/user-service/package.json
          action: rebuild
        - path: ./services/user-service/package-lock.json
          action: rebuild
        - path: ./services/auth-service/Config/dev.env
          action: rebuild
        - path: ./services/user-service
          target: /app
          action: sync

  articles-service:
    build:
      context: ./services/articles-service
      dockerfile: Dockerfile
    container_name: articles-service
    ports:
      - 7000:7000
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./services/articles-service/Config/dev.env
    networks:
      - services-network
    develop:
      watch:
        - path: ./services/articles-service/package.json
          action: rebuild
        - path: ./services/articles-service/package-lock.json
          action: rebuild
        - path: ./services/articles-service/Config/dev.env
          action: rebuild
        - path: ./services/articles-service
          target: /app
          action: sync

  chat-service:
    build:
      context: ./services/chat-service
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - redis
      - user-service
    env_file:
      - ./services/chat-service/Config/dev.env
    networks:
      - services-network
    develop:
      watch:
        - path: ./services/chat-service/package.json
          action: rebuild
        - path: ./services/chat-service/package-lock.json
          action: rebuild
        - path: ./services/chat-service/Config/dev.env
          action: rebuild
        - path: ./services/chat-service
          target: /app
          action: sync

  mongodb:
    image: mongo
    container_name: irlhistorymongo
    ports:
      - 27071:27017
    volumes:
      - irlhistory-data:/data/db
    networks:
      - services-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - services-network

volumes:
  irlhistory-data:
    driver: local
  grafana-data:
  prometheus-data:
  redis-data:

networks:
  services-network:
    driver: bridge
